ci: fix typo

diff --git a/.github/workflows/container-deploy.yml b/.github/workflows/container-deploy.yml
--- a/.github/workflows/container-deploy.yml
+++ b/.github/workflows/container-deploy.yml
@@ -62,7 +62,7 @@ jobs:
         script: |
           if [[ -f /home/off/${{ matrix.env }}/NO_DEPLOY ]]
           then
-            >2 echo "A NO_DEPLOY file exists (in /home/off/${{ matrix.env }}), failing !"
+            >&2 echo "A NO_DEPLOY file exists (in /home/off/${{ matrix.env }}), failing !"
             exit 1
           fi
 
